"""private messages

Revision ID: 6b3902b936ad
Revises: 944fe8c10960
Create Date: 2020-05-18 17:05:46.222538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3902b936ad'
down_revision = '944fe8c10960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'followers', 'users', ['followed_id'], ['id'])
    op.add_column('users', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_message_read_time')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    # ### end Alembic commands ###
