"""empty message

Revision ID: 944fe8c10960
Revises: a8768e867af5
Create Date: 2020-05-18 11:02:37.821082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944fe8c10960'
down_revision = 'a8768e867af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'followers', 'users', ['followed_id'], ['id'])
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
    #op.add_column('posts', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'language')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    # ### end Alembic commands ###
