"""add lanaguage to posts

Revision ID: d91ee4a3d081
Revises: a8768e867af5
Create Date: 2020-05-15 12:08:43.376221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91ee4a3d081'
down_revision = 'a8768e867af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'followers', 'users', ['followed_id'], ['id'])
    op.add_column('posts', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'language')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    # ### end Alembic commands ###
